# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = '2'

Vagrant.require_version '>= 1.4.3'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
    if Vagrant.has_plugin?('vagrant-omnibus')
      config.omnibus.chef_version = 'latest'
    end

    config.vm.box = 'bento/ubuntu-14.04'
    config.berkshelf.enabled = true

    config.vm.define 'server' do |server|
        server.vm.network :private_network, ip: '192.168.30.3'
        server.vm.provider :virtualbox do |vb|
            vb.memory = 2048
            vb.cpus = 2
        end
        server.vm.provision :chef_solo do |chef|
            chef.run_list = [
            'recipe[sensu_test::server]',
            'recipe[sensu_test::client]' ]
        end
    end
end
